let deck = [
  {
    cardNum: 1,
    suit: "♠︎",
    num: "2",
    numVal: 2,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/2_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 2,
    suit: "♠︎",
    num: "3",
    numVal: 3,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/3_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 3,
    suit: "♠︎",
    num: "4",
    numVal: 4,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/4_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 4,
    suit: "♠︎",
    num: "5",
    numVal: 5,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/5_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 5,
    suit: "♠︎",
    num: "6",
    numVal: 6,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/6_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 6,
    suit: "♠︎",
    num: "7",
    numVal: 7,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/7_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 7,
    suit: "♠︎",
    num: "8",
    numVal: 8,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/8_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 8,
    suit: "♠︎",
    num: "9",
    numVal: 9,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/9_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 9,
    suit: "♠︎",
    num: "10",
    numVal: 10,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/10_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 10,
    suit: "♠︎",
    num: "J",
    numVal: 11,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/jack_of_spades2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 11,
    suit: "♠︎",
    num: "Q",
    numVal: 12,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/queen_of_spades2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 12,
    suit: "♠︎",
    num: "K",
    numVal: 13,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/king_of_spades2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 13,
    suit: "♠︎",
    num: "A",
    numVal: 14,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/ace_of_spades.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 14,
    suit: "♢",
    num: "2",
    numVal: 2,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/2_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 15,
    suit: "♢",
    num: "3",
    numVal: 3,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/3_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 16,
    suit: "♢",
    num: "4",
    numVal: 4,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/4_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 17,
    suit: "♢",
    num: "5",
    numVal: 5,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/5_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 18,
    suit: "♢",
    num: "6",
    numVal: 6,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/6_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 19,
    suit: "♢",
    num: "7",
    numVal: 7,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/7_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 20,
    suit: "♢",
    num: "8",
    numVal: 8,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/8_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 21,
    suit: "♢",
    num: "9",
    numVal: 9,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/9_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 22,
    suit: "♢",
    num: "10",
    numVal: 10,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/10_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 23,
    suit: "♢",
    num: "K",
    numVal: 13,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/king_of_diamonds2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 24,
    suit: "♢",
    num: "Q",
    numVal: 12,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/queen_of_diamonds2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 25,
    suit: "♢",
    num: "J",
    numVal: 11,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/jack_of_diamonds2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 26,
    suit: "♢",
    num: "A",
    numVal: 14,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/ace_of_diamonds.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 27,
    suit: "♡",
    num: "2",
    numVal: 2,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/2_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 28,
    suit: "♡",
    num: "3",
    numVal: 3,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/3_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 29,
    suit: "♡",
    num: "4",
    numVal: 4,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/4_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 30,
    suit: "♡",
    num: "5",
    numVal: 5,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/5_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 31,
    suit: "♡",
    num: "6",
    numVal: 6,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/6_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 32,
    suit: "♡",
    num: "7",
    numVal: 7,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/7_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 33,
    suit: "♡",
    num: "8",
    numVal: 8,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/8_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 34,
    suit: "♡",
    num: "9",
    numVal: 9,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/9_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 35,
    suit: "♡",
    num: "10",
    numVal: 10,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/10_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 36,
    suit: "♡",
    num: "K",
    numVal: 13,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/king_of_hearts2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 37,
    suit: "♡",
    num: "Q",
    numVal: 12,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/queen_of_hearts2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 38,
    suit: "♡",
    num: "J",
    numVal: 11,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/jack_of_hearts2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 39,
    suit: "♡",
    num: "A",
    numVal: 14,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/ace_of_hearts.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 40,
    suit: "♣︎",
    num: "2",
    numVal: 2,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/2_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 41,
    suit: "♣︎",
    num: "3",
    numVal: 3,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/4_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 42,
    suit: "♣︎",
    num: "4",
    numVal: 4,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/4_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 43,
    suit: "♣︎",
    num: "5",
    numVal: 5,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/5_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 44,
    suit: "♣︎",
    num: "6",
    numVal: 6,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/6_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 45,
    suit: "♣︎",
    num: "7",
    numVal: 7,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/7_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 46,
    suit: "♣︎",
    num: "8",
    numVal: 8,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/8_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 47,
    suit: "♣︎",
    num: "9",
    numVal: 9,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/9_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 48,
    suit: "♣︎",
    num: "10",
    numVal: 10,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/10_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 49,
    suit: "♣︎",
    num: "J",
    numVal: 11,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/jack_of_clubs2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 50,
    suit: "♣︎",
    num: "Q",
    numVal: 12,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/queen_of_clubs2.png",

    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 51,
    suit: "♣︎",
    num: "K",
    numVal: 13,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/king_of_clubs2.png",
    isFlipped: false,
    hidden: false,
  },
  {
    cardNum: 52,
    suit: "♣︎",
    num: "A",
    numVal: 14,
    backImg: "https://imgs.abduzeedo.com/files/paul0v2/bicycle-cards/bc-11.jpg",
    frontImg: "/cards/ace_of_clubs.png",
    isFlipped: false,
    hidden: false,
  },
];

const shuffledeck = (deck) => {
  for (let i = 0; i < 1000; i++) {
    let location1 = Math.floor(Math.random() * deck.length);
    let location2 = Math.floor(Math.random() * deck.length);
    let tmp = deck[location1];
    deck[location1] = deck[location2];
    deck[location2] = tmp;
  }
  return deck;
};

export const dealHands = () => {
  shuffledeck(deck);
  let hand1 = []; //
  let hand2 = [];
  for (let i = 0; i < 26; i++) {
    if (i % 2 === 0) {
      hand1.push(deck[i]);
    } else {
      hand2.push(deck[i]);
    }
  }
  let player1 = assignProtectors(hand1);
  let player2 = assignProtectors(hand2);

  return {
    player1hand: player1,
    player2hand: player2,
  };
};

let assignProtectors = (hand) => {
  /*
      /row 2/
      array[4] protectors = array[0], array[1]
      array[5] protectors = array[1], array[2]
      array[6] protectors = array[2], array[3]
      
      /row 3/
      array[7] protectors = array[4]
      array[8] protectors = array[5]
      array[9] protectors = array[6]

      /row 4/
      array[10] protectors = array[7], array[8]
      array[11] protectors = array[8], array[9]
      
      /row 5/
      array[12] protectors = array[10], array[11]
    */
  return hand;
};
